### ISSUE TITLE
gtnnwr.add_graph()  raises IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Bhaaaal** [zjuwss/gnnwr#8]
I am now using pytorch 2.5.0+cu121

when runnning the official demo'**_demo_gtnnwr.ipynb_**', the '**_gtnnwr.add_graph()_**' rise an **IndexError: tuple index out of range**, i didnt find any possible way to solve it. So as the '**_demo_gnnwr.ipynb_**'.

I am a noob to ML.  I guess it might be a problem caused by version of torch?

Thanks a lot!

**Comment by Bhaaaal** [comment]
now i switch gnnwr version from the latest(0.1.12) to 0.1.0, **it works!**

**Comment by Y-nuclear** [comment]
We apologize for the oversight in not updating the notebook files in the **demo** folder while updating the code in the **src** folder. We will work on updating these notebooks promptly. In the meantime, you can continue your work with the **gnnwr version 0.1.11**. Thank you for your understanding and support! We will inform you in this issue once the update is completed.

**Comment by Bhaaaal** [comment]
> We apologize for the oversight in not updating the notebook files in the **demo** folder while updating the code in the **src** folder. We will work on updating these notebooks promptly. In the meantime, you can continue your work with the **gnnwr version 0.1.11**. Thank you for your understanding and support! We will inform you in this issue once the update is completed.

Appreciate your kind reply and help!  Wishing you all the best！ :D

**Comment by Y-nuclear** [comment]
Notebook has been updated to the latest version and is available. Thank you for your support!
